// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package signproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SignProxyClient is the client API for SignProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignProxyClient interface {
	// Method Version
	CreateCoin(ctx context.Context, in *CreateCoinRequest, opts ...grpc.CallOption) (*CreateCoinResponse, error)
	Transaction(ctx context.Context, opts ...grpc.CallOption) (SignProxy_TransactionClient, error)
}

type signProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewSignProxyClient(cc grpc.ClientConnInterface) SignProxyClient {
	return &signProxyClient{cc}
}

func (c *signProxyClient) CreateCoin(ctx context.Context, in *CreateCoinRequest, opts ...grpc.CallOption) (*CreateCoinResponse, error) {
	out := new(CreateCoinResponse)
	err := c.cc.Invoke(ctx, "/sphinx.proxy.v1.SignProxy/CreateCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signProxyClient) Transaction(ctx context.Context, opts ...grpc.CallOption) (SignProxy_TransactionClient, error) {
	stream, err := c.cc.NewStream(ctx, &SignProxy_ServiceDesc.Streams[0], "/sphinx.proxy.v1.SignProxy/Transaction", opts...)
	if err != nil {
		return nil, err
	}
	x := &signProxyTransactionClient{stream}
	return x, nil
}

type SignProxy_TransactionClient interface {
	Send(*TransactionResponse) error
	Recv() (*TransactionRequest, error)
	grpc.ClientStream
}

type signProxyTransactionClient struct {
	grpc.ClientStream
}

func (x *signProxyTransactionClient) Send(m *TransactionResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *signProxyTransactionClient) Recv() (*TransactionRequest, error) {
	m := new(TransactionRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SignProxyServer is the server API for SignProxy service.
// All implementations must embed UnimplementedSignProxyServer
// for forward compatibility
type SignProxyServer interface {
	// Method Version
	CreateCoin(context.Context, *CreateCoinRequest) (*CreateCoinResponse, error)
	Transaction(SignProxy_TransactionServer) error
	mustEmbedUnimplementedSignProxyServer()
}

// UnimplementedSignProxyServer must be embedded to have forward compatible implementations.
type UnimplementedSignProxyServer struct {
}

func (UnimplementedSignProxyServer) CreateCoin(context.Context, *CreateCoinRequest) (*CreateCoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCoin not implemented")
}
func (UnimplementedSignProxyServer) Transaction(SignProxy_TransactionServer) error {
	return status.Errorf(codes.Unimplemented, "method Transaction not implemented")
}
func (UnimplementedSignProxyServer) mustEmbedUnimplementedSignProxyServer() {}

// UnsafeSignProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignProxyServer will
// result in compilation errors.
type UnsafeSignProxyServer interface {
	mustEmbedUnimplementedSignProxyServer()
}

func RegisterSignProxyServer(s grpc.ServiceRegistrar, srv SignProxyServer) {
	s.RegisterService(&SignProxy_ServiceDesc, srv)
}

func _SignProxy_CreateCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignProxyServer).CreateCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sphinx.proxy.v1.SignProxy/CreateCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignProxyServer).CreateCoin(ctx, req.(*CreateCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignProxy_Transaction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SignProxyServer).Transaction(&signProxyTransactionServer{stream})
}

type SignProxy_TransactionServer interface {
	Send(*TransactionRequest) error
	Recv() (*TransactionResponse, error)
	grpc.ServerStream
}

type signProxyTransactionServer struct {
	grpc.ServerStream
}

func (x *signProxyTransactionServer) Send(m *TransactionRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *signProxyTransactionServer) Recv() (*TransactionResponse, error) {
	m := new(TransactionResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SignProxy_ServiceDesc is the grpc.ServiceDesc for SignProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sphinx.proxy.v1.SignProxy",
	HandlerType: (*SignProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCoin",
			Handler:    _SignProxy_CreateCoin_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transaction",
			Handler:       _SignProxy_Transaction_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "npool/signproxy/signproxy.proto",
}
