// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/sphinx-proxy/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/sphinx-proxy/pkg/db/ent/transaction"
)

// TransactionUpdate is the builder for updating Transaction entities.
type TransactionUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionMutation
}

// Where appends a list predicates to the TransactionUpdate builder.
func (tu *TransactionUpdate) Where(ps ...predicate.Transaction) *TransactionUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetNonce sets the "nonce" field.
func (tu *TransactionUpdate) SetNonce(u uint64) *TransactionUpdate {
	tu.mutation.ResetNonce()
	tu.mutation.SetNonce(u)
	return tu
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableNonce(u *uint64) *TransactionUpdate {
	if u != nil {
		tu.SetNonce(*u)
	}
	return tu
}

// AddNonce adds u to the "nonce" field.
func (tu *TransactionUpdate) AddNonce(u uint64) *TransactionUpdate {
	tu.mutation.AddNonce(u)
	return tu
}

// SetTransactionType sets the "transaction_type" field.
func (tu *TransactionUpdate) SetTransactionType(i int8) *TransactionUpdate {
	tu.mutation.ResetTransactionType()
	tu.mutation.SetTransactionType(i)
	return tu
}

// SetNillableTransactionType sets the "transaction_type" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableTransactionType(i *int8) *TransactionUpdate {
	if i != nil {
		tu.SetTransactionType(*i)
	}
	return tu
}

// AddTransactionType adds i to the "transaction_type" field.
func (tu *TransactionUpdate) AddTransactionType(i int8) *TransactionUpdate {
	tu.mutation.AddTransactionType(i)
	return tu
}

// SetCoinType sets the "coin_type" field.
func (tu *TransactionUpdate) SetCoinType(i int32) *TransactionUpdate {
	tu.mutation.ResetCoinType()
	tu.mutation.SetCoinType(i)
	return tu
}

// SetNillableCoinType sets the "coin_type" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableCoinType(i *int32) *TransactionUpdate {
	if i != nil {
		tu.SetCoinType(*i)
	}
	return tu
}

// AddCoinType adds i to the "coin_type" field.
func (tu *TransactionUpdate) AddCoinType(i int32) *TransactionUpdate {
	tu.mutation.AddCoinType(i)
	return tu
}

// SetTransactionID sets the "transaction_id" field.
func (tu *TransactionUpdate) SetTransactionID(s string) *TransactionUpdate {
	tu.mutation.SetTransactionID(s)
	return tu
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableTransactionID(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetTransactionID(*s)
	}
	return tu
}

// SetCid sets the "cid" field.
func (tu *TransactionUpdate) SetCid(s string) *TransactionUpdate {
	tu.mutation.SetCid(s)
	return tu
}

// SetNillableCid sets the "cid" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableCid(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetCid(*s)
	}
	return tu
}

// SetFrom sets the "from" field.
func (tu *TransactionUpdate) SetFrom(s string) *TransactionUpdate {
	tu.mutation.SetFrom(s)
	return tu
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableFrom(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetFrom(*s)
	}
	return tu
}

// SetTo sets the "to" field.
func (tu *TransactionUpdate) SetTo(s string) *TransactionUpdate {
	tu.mutation.SetTo(s)
	return tu
}

// SetNillableTo sets the "to" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableTo(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetTo(*s)
	}
	return tu
}

// SetValue sets the "value" field.
func (tu *TransactionUpdate) SetValue(f float64) *TransactionUpdate {
	tu.mutation.ResetValue()
	tu.mutation.SetValue(f)
	return tu
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableValue(f *float64) *TransactionUpdate {
	if f != nil {
		tu.SetValue(*f)
	}
	return tu
}

// AddValue adds f to the "value" field.
func (tu *TransactionUpdate) AddValue(f float64) *TransactionUpdate {
	tu.mutation.AddValue(f)
	return tu
}

// SetState sets the "state" field.
func (tu *TransactionUpdate) SetState(t transaction.State) *TransactionUpdate {
	tu.mutation.SetState(t)
	return tu
}

// SetCreateAt sets the "create_at" field.
func (tu *TransactionUpdate) SetCreateAt(u uint32) *TransactionUpdate {
	tu.mutation.ResetCreateAt()
	tu.mutation.SetCreateAt(u)
	return tu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableCreateAt(u *uint32) *TransactionUpdate {
	if u != nil {
		tu.SetCreateAt(*u)
	}
	return tu
}

// AddCreateAt adds u to the "create_at" field.
func (tu *TransactionUpdate) AddCreateAt(u uint32) *TransactionUpdate {
	tu.mutation.AddCreateAt(u)
	return tu
}

// SetUpdateAt sets the "update_at" field.
func (tu *TransactionUpdate) SetUpdateAt(u uint32) *TransactionUpdate {
	tu.mutation.ResetUpdateAt()
	tu.mutation.SetUpdateAt(u)
	return tu
}

// AddUpdateAt adds u to the "update_at" field.
func (tu *TransactionUpdate) AddUpdateAt(u uint32) *TransactionUpdate {
	tu.mutation.AddUpdateAt(u)
	return tu
}

// SetDeleteAt sets the "delete_at" field.
func (tu *TransactionUpdate) SetDeleteAt(u uint32) *TransactionUpdate {
	tu.mutation.ResetDeleteAt()
	tu.mutation.SetDeleteAt(u)
	return tu
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableDeleteAt(u *uint32) *TransactionUpdate {
	if u != nil {
		tu.SetDeleteAt(*u)
	}
	return tu
}

// AddDeleteAt adds u to the "delete_at" field.
func (tu *TransactionUpdate) AddDeleteAt(u uint32) *TransactionUpdate {
	tu.mutation.AddDeleteAt(u)
	return tu
}

// Mutation returns the TransactionMutation object of the builder.
func (tu *TransactionUpdate) Mutation() *TransactionMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TransactionUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	tu.defaults()
	if len(tu.hooks) == 0 {
		if err = tu.check(); err != nil {
			return 0, err
		}
		affected, err = tu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TransactionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tu.check(); err != nil {
				return 0, err
			}
			tu.mutation = mutation
			affected, err = tu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tu.hooks) - 1; i >= 0; i-- {
			if tu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TransactionUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TransactionUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TransactionUpdate) defaults() {
	if _, ok := tu.mutation.UpdateAt(); !ok {
		v := transaction.UpdateDefaultUpdateAt()
		tu.mutation.SetUpdateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TransactionUpdate) check() error {
	if v, ok := tu.mutation.TransactionID(); ok {
		if err := transaction.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf("ent: validator failed for field \"transaction_id\": %w", err)}
		}
	}
	if v, ok := tu.mutation.Cid(); ok {
		if err := transaction.CidValidator(v); err != nil {
			return &ValidationError{Name: "cid", err: fmt.Errorf("ent: validator failed for field \"cid\": %w", err)}
		}
	}
	if v, ok := tu.mutation.From(); ok {
		if err := transaction.FromValidator(v); err != nil {
			return &ValidationError{Name: "from", err: fmt.Errorf("ent: validator failed for field \"from\": %w", err)}
		}
	}
	if v, ok := tu.mutation.To(); ok {
		if err := transaction.ToValidator(v); err != nil {
			return &ValidationError{Name: "to", err: fmt.Errorf("ent: validator failed for field \"to\": %w", err)}
		}
	}
	if v, ok := tu.mutation.State(); ok {
		if err := transaction.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf("ent: validator failed for field \"state\": %w", err)}
		}
	}
	return nil
}

func (tu *TransactionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   transaction.Table,
			Columns: transaction.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: transaction.FieldID,
			},
		},
	}
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Nonce(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: transaction.FieldNonce,
		})
	}
	if value, ok := tu.mutation.AddedNonce(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: transaction.FieldNonce,
		})
	}
	if value, ok := tu.mutation.TransactionType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: transaction.FieldTransactionType,
		})
	}
	if value, ok := tu.mutation.AddedTransactionType(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: transaction.FieldTransactionType,
		})
	}
	if value, ok := tu.mutation.CoinType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldCoinType,
		})
	}
	if value, ok := tu.mutation.AddedCoinType(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldCoinType,
		})
	}
	if value, ok := tu.mutation.TransactionID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldTransactionID,
		})
	}
	if value, ok := tu.mutation.Cid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldCid,
		})
	}
	if value, ok := tu.mutation.From(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldFrom,
		})
	}
	if value, ok := tu.mutation.To(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldTo,
		})
	}
	if value, ok := tu.mutation.Value(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: transaction.FieldValue,
		})
	}
	if value, ok := tu.mutation.AddedValue(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: transaction.FieldValue,
		})
	}
	if value, ok := tu.mutation.State(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: transaction.FieldState,
		})
	}
	if value, ok := tu.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldCreateAt,
		})
	}
	if value, ok := tu.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldCreateAt,
		})
	}
	if value, ok := tu.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldUpdateAt,
		})
	}
	if value, ok := tu.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldUpdateAt,
		})
	}
	if value, ok := tu.mutation.DeleteAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldDeleteAt,
		})
	}
	if value, ok := tu.mutation.AddedDeleteAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldDeleteAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// TransactionUpdateOne is the builder for updating a single Transaction entity.
type TransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionMutation
}

// SetNonce sets the "nonce" field.
func (tuo *TransactionUpdateOne) SetNonce(u uint64) *TransactionUpdateOne {
	tuo.mutation.ResetNonce()
	tuo.mutation.SetNonce(u)
	return tuo
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableNonce(u *uint64) *TransactionUpdateOne {
	if u != nil {
		tuo.SetNonce(*u)
	}
	return tuo
}

// AddNonce adds u to the "nonce" field.
func (tuo *TransactionUpdateOne) AddNonce(u uint64) *TransactionUpdateOne {
	tuo.mutation.AddNonce(u)
	return tuo
}

// SetTransactionType sets the "transaction_type" field.
func (tuo *TransactionUpdateOne) SetTransactionType(i int8) *TransactionUpdateOne {
	tuo.mutation.ResetTransactionType()
	tuo.mutation.SetTransactionType(i)
	return tuo
}

// SetNillableTransactionType sets the "transaction_type" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableTransactionType(i *int8) *TransactionUpdateOne {
	if i != nil {
		tuo.SetTransactionType(*i)
	}
	return tuo
}

// AddTransactionType adds i to the "transaction_type" field.
func (tuo *TransactionUpdateOne) AddTransactionType(i int8) *TransactionUpdateOne {
	tuo.mutation.AddTransactionType(i)
	return tuo
}

// SetCoinType sets the "coin_type" field.
func (tuo *TransactionUpdateOne) SetCoinType(i int32) *TransactionUpdateOne {
	tuo.mutation.ResetCoinType()
	tuo.mutation.SetCoinType(i)
	return tuo
}

// SetNillableCoinType sets the "coin_type" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableCoinType(i *int32) *TransactionUpdateOne {
	if i != nil {
		tuo.SetCoinType(*i)
	}
	return tuo
}

// AddCoinType adds i to the "coin_type" field.
func (tuo *TransactionUpdateOne) AddCoinType(i int32) *TransactionUpdateOne {
	tuo.mutation.AddCoinType(i)
	return tuo
}

// SetTransactionID sets the "transaction_id" field.
func (tuo *TransactionUpdateOne) SetTransactionID(s string) *TransactionUpdateOne {
	tuo.mutation.SetTransactionID(s)
	return tuo
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableTransactionID(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetTransactionID(*s)
	}
	return tuo
}

// SetCid sets the "cid" field.
func (tuo *TransactionUpdateOne) SetCid(s string) *TransactionUpdateOne {
	tuo.mutation.SetCid(s)
	return tuo
}

// SetNillableCid sets the "cid" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableCid(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetCid(*s)
	}
	return tuo
}

// SetFrom sets the "from" field.
func (tuo *TransactionUpdateOne) SetFrom(s string) *TransactionUpdateOne {
	tuo.mutation.SetFrom(s)
	return tuo
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableFrom(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetFrom(*s)
	}
	return tuo
}

// SetTo sets the "to" field.
func (tuo *TransactionUpdateOne) SetTo(s string) *TransactionUpdateOne {
	tuo.mutation.SetTo(s)
	return tuo
}

// SetNillableTo sets the "to" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableTo(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetTo(*s)
	}
	return tuo
}

// SetValue sets the "value" field.
func (tuo *TransactionUpdateOne) SetValue(f float64) *TransactionUpdateOne {
	tuo.mutation.ResetValue()
	tuo.mutation.SetValue(f)
	return tuo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableValue(f *float64) *TransactionUpdateOne {
	if f != nil {
		tuo.SetValue(*f)
	}
	return tuo
}

// AddValue adds f to the "value" field.
func (tuo *TransactionUpdateOne) AddValue(f float64) *TransactionUpdateOne {
	tuo.mutation.AddValue(f)
	return tuo
}

// SetState sets the "state" field.
func (tuo *TransactionUpdateOne) SetState(t transaction.State) *TransactionUpdateOne {
	tuo.mutation.SetState(t)
	return tuo
}

// SetCreateAt sets the "create_at" field.
func (tuo *TransactionUpdateOne) SetCreateAt(u uint32) *TransactionUpdateOne {
	tuo.mutation.ResetCreateAt()
	tuo.mutation.SetCreateAt(u)
	return tuo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableCreateAt(u *uint32) *TransactionUpdateOne {
	if u != nil {
		tuo.SetCreateAt(*u)
	}
	return tuo
}

// AddCreateAt adds u to the "create_at" field.
func (tuo *TransactionUpdateOne) AddCreateAt(u uint32) *TransactionUpdateOne {
	tuo.mutation.AddCreateAt(u)
	return tuo
}

// SetUpdateAt sets the "update_at" field.
func (tuo *TransactionUpdateOne) SetUpdateAt(u uint32) *TransactionUpdateOne {
	tuo.mutation.ResetUpdateAt()
	tuo.mutation.SetUpdateAt(u)
	return tuo
}

// AddUpdateAt adds u to the "update_at" field.
func (tuo *TransactionUpdateOne) AddUpdateAt(u uint32) *TransactionUpdateOne {
	tuo.mutation.AddUpdateAt(u)
	return tuo
}

// SetDeleteAt sets the "delete_at" field.
func (tuo *TransactionUpdateOne) SetDeleteAt(u uint32) *TransactionUpdateOne {
	tuo.mutation.ResetDeleteAt()
	tuo.mutation.SetDeleteAt(u)
	return tuo
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableDeleteAt(u *uint32) *TransactionUpdateOne {
	if u != nil {
		tuo.SetDeleteAt(*u)
	}
	return tuo
}

// AddDeleteAt adds u to the "delete_at" field.
func (tuo *TransactionUpdateOne) AddDeleteAt(u uint32) *TransactionUpdateOne {
	tuo.mutation.AddDeleteAt(u)
	return tuo
}

// Mutation returns the TransactionMutation object of the builder.
func (tuo *TransactionUpdateOne) Mutation() *TransactionMutation {
	return tuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TransactionUpdateOne) Select(field string, fields ...string) *TransactionUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Transaction entity.
func (tuo *TransactionUpdateOne) Save(ctx context.Context) (*Transaction, error) {
	var (
		err  error
		node *Transaction
	)
	tuo.defaults()
	if len(tuo.hooks) == 0 {
		if err = tuo.check(); err != nil {
			return nil, err
		}
		node, err = tuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TransactionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tuo.check(); err != nil {
				return nil, err
			}
			tuo.mutation = mutation
			node, err = tuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tuo.hooks) - 1; i >= 0; i-- {
			if tuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TransactionUpdateOne) SaveX(ctx context.Context) *Transaction {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TransactionUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TransactionUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdateAt(); !ok {
		v := transaction.UpdateDefaultUpdateAt()
		tuo.mutation.SetUpdateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TransactionUpdateOne) check() error {
	if v, ok := tuo.mutation.TransactionID(); ok {
		if err := transaction.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf("ent: validator failed for field \"transaction_id\": %w", err)}
		}
	}
	if v, ok := tuo.mutation.Cid(); ok {
		if err := transaction.CidValidator(v); err != nil {
			return &ValidationError{Name: "cid", err: fmt.Errorf("ent: validator failed for field \"cid\": %w", err)}
		}
	}
	if v, ok := tuo.mutation.From(); ok {
		if err := transaction.FromValidator(v); err != nil {
			return &ValidationError{Name: "from", err: fmt.Errorf("ent: validator failed for field \"from\": %w", err)}
		}
	}
	if v, ok := tuo.mutation.To(); ok {
		if err := transaction.ToValidator(v); err != nil {
			return &ValidationError{Name: "to", err: fmt.Errorf("ent: validator failed for field \"to\": %w", err)}
		}
	}
	if v, ok := tuo.mutation.State(); ok {
		if err := transaction.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf("ent: validator failed for field \"state\": %w", err)}
		}
	}
	return nil
}

func (tuo *TransactionUpdateOne) sqlSave(ctx context.Context) (_node *Transaction, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   transaction.Table,
			Columns: transaction.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: transaction.FieldID,
			},
		},
	}
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Transaction.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for _, f := range fields {
			if !transaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Nonce(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: transaction.FieldNonce,
		})
	}
	if value, ok := tuo.mutation.AddedNonce(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: transaction.FieldNonce,
		})
	}
	if value, ok := tuo.mutation.TransactionType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: transaction.FieldTransactionType,
		})
	}
	if value, ok := tuo.mutation.AddedTransactionType(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: transaction.FieldTransactionType,
		})
	}
	if value, ok := tuo.mutation.CoinType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldCoinType,
		})
	}
	if value, ok := tuo.mutation.AddedCoinType(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldCoinType,
		})
	}
	if value, ok := tuo.mutation.TransactionID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldTransactionID,
		})
	}
	if value, ok := tuo.mutation.Cid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldCid,
		})
	}
	if value, ok := tuo.mutation.From(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldFrom,
		})
	}
	if value, ok := tuo.mutation.To(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldTo,
		})
	}
	if value, ok := tuo.mutation.Value(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: transaction.FieldValue,
		})
	}
	if value, ok := tuo.mutation.AddedValue(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: transaction.FieldValue,
		})
	}
	if value, ok := tuo.mutation.State(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: transaction.FieldState,
		})
	}
	if value, ok := tuo.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldCreateAt,
		})
	}
	if value, ok := tuo.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldCreateAt,
		})
	}
	if value, ok := tuo.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldUpdateAt,
		})
	}
	if value, ok := tuo.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldUpdateAt,
		})
	}
	if value, ok := tuo.mutation.DeleteAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldDeleteAt,
		})
	}
	if value, ok := tuo.mutation.AddedDeleteAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldDeleteAt,
		})
	}
	_node = &Transaction{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
