// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/message/npool/sphinxplugin"
	"github.com/NpoolPlatform/sphinx-proxy/pkg/db/ent/transaction"
	"github.com/google/uuid"
)

// TransactionCreate is the builder for creating a Transaction entity.
type TransactionCreate struct {
	config
	mutation *TransactionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCoinType sets the "coin_type" field.
func (tc *TransactionCreate) SetCoinType(i int32) *TransactionCreate {
	tc.mutation.SetCoinType(i)
	return tc
}

// SetNillableCoinType sets the "coin_type" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableCoinType(i *int32) *TransactionCreate {
	if i != nil {
		tc.SetCoinType(*i)
	}
	return tc
}

// SetNonce sets the "nonce" field.
func (tc *TransactionCreate) SetNonce(u uint64) *TransactionCreate {
	tc.mutation.SetNonce(u)
	return tc
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableNonce(u *uint64) *TransactionCreate {
	if u != nil {
		tc.SetNonce(*u)
	}
	return tc
}

// SetUtxo sets the "utxo" field.
func (tc *TransactionCreate) SetUtxo(s []*sphinxplugin.Unspent) *TransactionCreate {
	tc.mutation.SetUtxo(s)
	return tc
}

// SetPre sets the "pre" field.
func (tc *TransactionCreate) SetPre(s *sphinxplugin.Unspent) *TransactionCreate {
	tc.mutation.SetPre(s)
	return tc
}

// SetTransactionType sets the "transaction_type" field.
func (tc *TransactionCreate) SetTransactionType(i int8) *TransactionCreate {
	tc.mutation.SetTransactionType(i)
	return tc
}

// SetNillableTransactionType sets the "transaction_type" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableTransactionType(i *int8) *TransactionCreate {
	if i != nil {
		tc.SetTransactionType(*i)
	}
	return tc
}

// SetRecentBhash sets the "recent_bhash" field.
func (tc *TransactionCreate) SetRecentBhash(s string) *TransactionCreate {
	tc.mutation.SetRecentBhash(s)
	return tc
}

// SetNillableRecentBhash sets the "recent_bhash" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableRecentBhash(s *string) *TransactionCreate {
	if s != nil {
		tc.SetRecentBhash(*s)
	}
	return tc
}

// SetTxData sets the "tx_data" field.
func (tc *TransactionCreate) SetTxData(b []byte) *TransactionCreate {
	tc.mutation.SetTxData(b)
	return tc
}

// SetTransactionID sets the "transaction_id" field.
func (tc *TransactionCreate) SetTransactionID(s string) *TransactionCreate {
	tc.mutation.SetTransactionID(s)
	return tc
}

// SetCid sets the "cid" field.
func (tc *TransactionCreate) SetCid(s string) *TransactionCreate {
	tc.mutation.SetCid(s)
	return tc
}

// SetNillableCid sets the "cid" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableCid(s *string) *TransactionCreate {
	if s != nil {
		tc.SetCid(*s)
	}
	return tc
}

// SetExitCode sets the "exit_code" field.
func (tc *TransactionCreate) SetExitCode(i int64) *TransactionCreate {
	tc.mutation.SetExitCode(i)
	return tc
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableExitCode(i *int64) *TransactionCreate {
	if i != nil {
		tc.SetExitCode(*i)
	}
	return tc
}

// SetName sets the "name" field.
func (tc *TransactionCreate) SetName(s string) *TransactionCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableName(s *string) *TransactionCreate {
	if s != nil {
		tc.SetName(*s)
	}
	return tc
}

// SetFrom sets the "from" field.
func (tc *TransactionCreate) SetFrom(s string) *TransactionCreate {
	tc.mutation.SetFrom(s)
	return tc
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableFrom(s *string) *TransactionCreate {
	if s != nil {
		tc.SetFrom(*s)
	}
	return tc
}

// SetTo sets the "to" field.
func (tc *TransactionCreate) SetTo(s string) *TransactionCreate {
	tc.mutation.SetTo(s)
	return tc
}

// SetNillableTo sets the "to" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableTo(s *string) *TransactionCreate {
	if s != nil {
		tc.SetTo(*s)
	}
	return tc
}

// SetMemo sets the "memo" field.
func (tc *TransactionCreate) SetMemo(s string) *TransactionCreate {
	tc.mutation.SetMemo(s)
	return tc
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableMemo(s *string) *TransactionCreate {
	if s != nil {
		tc.SetMemo(*s)
	}
	return tc
}

// SetAmount sets the "amount" field.
func (tc *TransactionCreate) SetAmount(u uint64) *TransactionCreate {
	tc.mutation.SetAmount(u)
	return tc
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableAmount(u *uint64) *TransactionCreate {
	if u != nil {
		tc.SetAmount(*u)
	}
	return tc
}

// SetPayload sets the "payload" field.
func (tc *TransactionCreate) SetPayload(b []byte) *TransactionCreate {
	tc.mutation.SetPayload(b)
	return tc
}

// SetState sets the "state" field.
func (tc *TransactionCreate) SetState(u uint8) *TransactionCreate {
	tc.mutation.SetState(u)
	return tc
}

// SetNillableState sets the "state" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableState(u *uint8) *TransactionCreate {
	if u != nil {
		tc.SetState(*u)
	}
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *TransactionCreate) SetCreatedAt(u uint32) *TransactionCreate {
	tc.mutation.SetCreatedAt(u)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableCreatedAt(u *uint32) *TransactionCreate {
	if u != nil {
		tc.SetCreatedAt(*u)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *TransactionCreate) SetUpdatedAt(u uint32) *TransactionCreate {
	tc.mutation.SetUpdatedAt(u)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableUpdatedAt(u *uint32) *TransactionCreate {
	if u != nil {
		tc.SetUpdatedAt(*u)
	}
	return tc
}

// SetDeletedAt sets the "deleted_at" field.
func (tc *TransactionCreate) SetDeletedAt(u uint32) *TransactionCreate {
	tc.mutation.SetDeletedAt(u)
	return tc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableDeletedAt(u *uint32) *TransactionCreate {
	if u != nil {
		tc.SetDeletedAt(*u)
	}
	return tc
}

// SetID sets the "id" field.
func (tc *TransactionCreate) SetID(u uuid.UUID) *TransactionCreate {
	tc.mutation.SetID(u)
	return tc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tc *TransactionCreate) SetNillableID(u *uuid.UUID) *TransactionCreate {
	if u != nil {
		tc.SetID(*u)
	}
	return tc
}

// Mutation returns the TransactionMutation object of the builder.
func (tc *TransactionCreate) Mutation() *TransactionMutation {
	return tc.mutation
}

// Save creates the Transaction in the database.
func (tc *TransactionCreate) Save(ctx context.Context) (*Transaction, error) {
	var (
		err  error
		node *Transaction
	)
	tc.defaults()
	if len(tc.hooks) == 0 {
		if err = tc.check(); err != nil {
			return nil, err
		}
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TransactionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tc.check(); err != nil {
				return nil, err
			}
			tc.mutation = mutation
			if node, err = tc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			if tc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, tc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Transaction)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from TransactionMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TransactionCreate) SaveX(ctx context.Context) *Transaction {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TransactionCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TransactionCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TransactionCreate) defaults() {
	if _, ok := tc.mutation.CoinType(); !ok {
		v := transaction.DefaultCoinType
		tc.mutation.SetCoinType(v)
	}
	if _, ok := tc.mutation.Nonce(); !ok {
		v := transaction.DefaultNonce
		tc.mutation.SetNonce(v)
	}
	if _, ok := tc.mutation.Utxo(); !ok {
		v := transaction.DefaultUtxo
		tc.mutation.SetUtxo(v)
	}
	if _, ok := tc.mutation.Pre(); !ok {
		v := transaction.DefaultPre
		tc.mutation.SetPre(v)
	}
	if _, ok := tc.mutation.TransactionType(); !ok {
		v := transaction.DefaultTransactionType
		tc.mutation.SetTransactionType(v)
	}
	if _, ok := tc.mutation.RecentBhash(); !ok {
		v := transaction.DefaultRecentBhash
		tc.mutation.SetRecentBhash(v)
	}
	if _, ok := tc.mutation.TxData(); !ok {
		v := transaction.DefaultTxData
		tc.mutation.SetTxData(v)
	}
	if _, ok := tc.mutation.Cid(); !ok {
		v := transaction.DefaultCid
		tc.mutation.SetCid(v)
	}
	if _, ok := tc.mutation.ExitCode(); !ok {
		v := transaction.DefaultExitCode
		tc.mutation.SetExitCode(v)
	}
	if _, ok := tc.mutation.Name(); !ok {
		v := transaction.DefaultName
		tc.mutation.SetName(v)
	}
	if _, ok := tc.mutation.From(); !ok {
		v := transaction.DefaultFrom
		tc.mutation.SetFrom(v)
	}
	if _, ok := tc.mutation.To(); !ok {
		v := transaction.DefaultTo
		tc.mutation.SetTo(v)
	}
	if _, ok := tc.mutation.Memo(); !ok {
		v := transaction.DefaultMemo
		tc.mutation.SetMemo(v)
	}
	if _, ok := tc.mutation.Amount(); !ok {
		v := transaction.DefaultAmount
		tc.mutation.SetAmount(v)
	}
	if _, ok := tc.mutation.Payload(); !ok {
		v := transaction.DefaultPayload
		tc.mutation.SetPayload(v)
	}
	if _, ok := tc.mutation.State(); !ok {
		v := transaction.DefaultState
		tc.mutation.SetState(v)
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := transaction.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := transaction.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tc.mutation.DeletedAt(); !ok {
		v := transaction.DefaultDeletedAt()
		tc.mutation.SetDeletedAt(v)
	}
	if _, ok := tc.mutation.ID(); !ok {
		v := transaction.DefaultID()
		tc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TransactionCreate) check() error {
	if _, ok := tc.mutation.TransactionID(); !ok {
		return &ValidationError{Name: "transaction_id", err: errors.New(`ent: missing required field "Transaction.transaction_id"`)}
	}
	if v, ok := tc.mutation.Payload(); ok {
		if err := transaction.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "Transaction.payload": %w`, err)}
		}
	}
	return nil
}

func (tc *TransactionCreate) sqlSave(ctx context.Context) (*Transaction, error) {
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (tc *TransactionCreate) createSpec() (*Transaction, *sqlgraph.CreateSpec) {
	var (
		_node = &Transaction{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: transaction.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: transaction.FieldID,
			},
		}
	)
	_spec.OnConflict = tc.conflict
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tc.mutation.CoinType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: transaction.FieldCoinType,
		})
		_node.CoinType = value
	}
	if value, ok := tc.mutation.Nonce(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: transaction.FieldNonce,
		})
		_node.Nonce = value
	}
	if value, ok := tc.mutation.Utxo(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: transaction.FieldUtxo,
		})
		_node.Utxo = value
	}
	if value, ok := tc.mutation.Pre(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: transaction.FieldPre,
		})
		_node.Pre = value
	}
	if value, ok := tc.mutation.TransactionType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: transaction.FieldTransactionType,
		})
		_node.TransactionType = value
	}
	if value, ok := tc.mutation.RecentBhash(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldRecentBhash,
		})
		_node.RecentBhash = value
	}
	if value, ok := tc.mutation.TxData(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: transaction.FieldTxData,
		})
		_node.TxData = value
	}
	if value, ok := tc.mutation.TransactionID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldTransactionID,
		})
		_node.TransactionID = value
	}
	if value, ok := tc.mutation.Cid(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldCid,
		})
		_node.Cid = value
	}
	if value, ok := tc.mutation.ExitCode(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: transaction.FieldExitCode,
		})
		_node.ExitCode = value
	}
	if value, ok := tc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldName,
		})
		_node.Name = value
	}
	if value, ok := tc.mutation.From(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldFrom,
		})
		_node.From = value
	}
	if value, ok := tc.mutation.To(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldTo,
		})
		_node.To = value
	}
	if value, ok := tc.mutation.Memo(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: transaction.FieldMemo,
		})
		_node.Memo = value
	}
	if value, ok := tc.mutation.Amount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: transaction.FieldAmount,
		})
		_node.Amount = value
	}
	if value, ok := tc.mutation.Payload(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: transaction.FieldPayload,
		})
		_node.Payload = value
	}
	if value, ok := tc.mutation.State(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  value,
			Column: transaction.FieldState,
		})
		_node.State = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := tc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: transaction.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Transaction.Create().
//		SetCoinType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TransactionUpsert) {
//			SetCoinType(v+v).
//		}).
//		Exec(ctx)
func (tc *TransactionCreate) OnConflict(opts ...sql.ConflictOption) *TransactionUpsertOne {
	tc.conflict = opts
	return &TransactionUpsertOne{
		create: tc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Transaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tc *TransactionCreate) OnConflictColumns(columns ...string) *TransactionUpsertOne {
	tc.conflict = append(tc.conflict, sql.ConflictColumns(columns...))
	return &TransactionUpsertOne{
		create: tc,
	}
}

type (
	// TransactionUpsertOne is the builder for "upsert"-ing
	//  one Transaction node.
	TransactionUpsertOne struct {
		create *TransactionCreate
	}

	// TransactionUpsert is the "OnConflict" setter.
	TransactionUpsert struct {
		*sql.UpdateSet
	}
)

// SetCoinType sets the "coin_type" field.
func (u *TransactionUpsert) SetCoinType(v int32) *TransactionUpsert {
	u.Set(transaction.FieldCoinType, v)
	return u
}

// UpdateCoinType sets the "coin_type" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateCoinType() *TransactionUpsert {
	u.SetExcluded(transaction.FieldCoinType)
	return u
}

// AddCoinType adds v to the "coin_type" field.
func (u *TransactionUpsert) AddCoinType(v int32) *TransactionUpsert {
	u.Add(transaction.FieldCoinType, v)
	return u
}

// ClearCoinType clears the value of the "coin_type" field.
func (u *TransactionUpsert) ClearCoinType() *TransactionUpsert {
	u.SetNull(transaction.FieldCoinType)
	return u
}

// SetNonce sets the "nonce" field.
func (u *TransactionUpsert) SetNonce(v uint64) *TransactionUpsert {
	u.Set(transaction.FieldNonce, v)
	return u
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateNonce() *TransactionUpsert {
	u.SetExcluded(transaction.FieldNonce)
	return u
}

// AddNonce adds v to the "nonce" field.
func (u *TransactionUpsert) AddNonce(v uint64) *TransactionUpsert {
	u.Add(transaction.FieldNonce, v)
	return u
}

// ClearNonce clears the value of the "nonce" field.
func (u *TransactionUpsert) ClearNonce() *TransactionUpsert {
	u.SetNull(transaction.FieldNonce)
	return u
}

// SetUtxo sets the "utxo" field.
func (u *TransactionUpsert) SetUtxo(v []*sphinxplugin.Unspent) *TransactionUpsert {
	u.Set(transaction.FieldUtxo, v)
	return u
}

// UpdateUtxo sets the "utxo" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateUtxo() *TransactionUpsert {
	u.SetExcluded(transaction.FieldUtxo)
	return u
}

// ClearUtxo clears the value of the "utxo" field.
func (u *TransactionUpsert) ClearUtxo() *TransactionUpsert {
	u.SetNull(transaction.FieldUtxo)
	return u
}

// SetPre sets the "pre" field.
func (u *TransactionUpsert) SetPre(v *sphinxplugin.Unspent) *TransactionUpsert {
	u.Set(transaction.FieldPre, v)
	return u
}

// UpdatePre sets the "pre" field to the value that was provided on create.
func (u *TransactionUpsert) UpdatePre() *TransactionUpsert {
	u.SetExcluded(transaction.FieldPre)
	return u
}

// ClearPre clears the value of the "pre" field.
func (u *TransactionUpsert) ClearPre() *TransactionUpsert {
	u.SetNull(transaction.FieldPre)
	return u
}

// SetTransactionType sets the "transaction_type" field.
func (u *TransactionUpsert) SetTransactionType(v int8) *TransactionUpsert {
	u.Set(transaction.FieldTransactionType, v)
	return u
}

// UpdateTransactionType sets the "transaction_type" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateTransactionType() *TransactionUpsert {
	u.SetExcluded(transaction.FieldTransactionType)
	return u
}

// AddTransactionType adds v to the "transaction_type" field.
func (u *TransactionUpsert) AddTransactionType(v int8) *TransactionUpsert {
	u.Add(transaction.FieldTransactionType, v)
	return u
}

// ClearTransactionType clears the value of the "transaction_type" field.
func (u *TransactionUpsert) ClearTransactionType() *TransactionUpsert {
	u.SetNull(transaction.FieldTransactionType)
	return u
}

// SetRecentBhash sets the "recent_bhash" field.
func (u *TransactionUpsert) SetRecentBhash(v string) *TransactionUpsert {
	u.Set(transaction.FieldRecentBhash, v)
	return u
}

// UpdateRecentBhash sets the "recent_bhash" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateRecentBhash() *TransactionUpsert {
	u.SetExcluded(transaction.FieldRecentBhash)
	return u
}

// ClearRecentBhash clears the value of the "recent_bhash" field.
func (u *TransactionUpsert) ClearRecentBhash() *TransactionUpsert {
	u.SetNull(transaction.FieldRecentBhash)
	return u
}

// SetTxData sets the "tx_data" field.
func (u *TransactionUpsert) SetTxData(v []byte) *TransactionUpsert {
	u.Set(transaction.FieldTxData, v)
	return u
}

// UpdateTxData sets the "tx_data" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateTxData() *TransactionUpsert {
	u.SetExcluded(transaction.FieldTxData)
	return u
}

// ClearTxData clears the value of the "tx_data" field.
func (u *TransactionUpsert) ClearTxData() *TransactionUpsert {
	u.SetNull(transaction.FieldTxData)
	return u
}

// SetTransactionID sets the "transaction_id" field.
func (u *TransactionUpsert) SetTransactionID(v string) *TransactionUpsert {
	u.Set(transaction.FieldTransactionID, v)
	return u
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateTransactionID() *TransactionUpsert {
	u.SetExcluded(transaction.FieldTransactionID)
	return u
}

// SetCid sets the "cid" field.
func (u *TransactionUpsert) SetCid(v string) *TransactionUpsert {
	u.Set(transaction.FieldCid, v)
	return u
}

// UpdateCid sets the "cid" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateCid() *TransactionUpsert {
	u.SetExcluded(transaction.FieldCid)
	return u
}

// ClearCid clears the value of the "cid" field.
func (u *TransactionUpsert) ClearCid() *TransactionUpsert {
	u.SetNull(transaction.FieldCid)
	return u
}

// SetExitCode sets the "exit_code" field.
func (u *TransactionUpsert) SetExitCode(v int64) *TransactionUpsert {
	u.Set(transaction.FieldExitCode, v)
	return u
}

// UpdateExitCode sets the "exit_code" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateExitCode() *TransactionUpsert {
	u.SetExcluded(transaction.FieldExitCode)
	return u
}

// AddExitCode adds v to the "exit_code" field.
func (u *TransactionUpsert) AddExitCode(v int64) *TransactionUpsert {
	u.Add(transaction.FieldExitCode, v)
	return u
}

// ClearExitCode clears the value of the "exit_code" field.
func (u *TransactionUpsert) ClearExitCode() *TransactionUpsert {
	u.SetNull(transaction.FieldExitCode)
	return u
}

// SetName sets the "name" field.
func (u *TransactionUpsert) SetName(v string) *TransactionUpsert {
	u.Set(transaction.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateName() *TransactionUpsert {
	u.SetExcluded(transaction.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *TransactionUpsert) ClearName() *TransactionUpsert {
	u.SetNull(transaction.FieldName)
	return u
}

// SetFrom sets the "from" field.
func (u *TransactionUpsert) SetFrom(v string) *TransactionUpsert {
	u.Set(transaction.FieldFrom, v)
	return u
}

// UpdateFrom sets the "from" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateFrom() *TransactionUpsert {
	u.SetExcluded(transaction.FieldFrom)
	return u
}

// ClearFrom clears the value of the "from" field.
func (u *TransactionUpsert) ClearFrom() *TransactionUpsert {
	u.SetNull(transaction.FieldFrom)
	return u
}

// SetTo sets the "to" field.
func (u *TransactionUpsert) SetTo(v string) *TransactionUpsert {
	u.Set(transaction.FieldTo, v)
	return u
}

// UpdateTo sets the "to" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateTo() *TransactionUpsert {
	u.SetExcluded(transaction.FieldTo)
	return u
}

// ClearTo clears the value of the "to" field.
func (u *TransactionUpsert) ClearTo() *TransactionUpsert {
	u.SetNull(transaction.FieldTo)
	return u
}

// SetMemo sets the "memo" field.
func (u *TransactionUpsert) SetMemo(v string) *TransactionUpsert {
	u.Set(transaction.FieldMemo, v)
	return u
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateMemo() *TransactionUpsert {
	u.SetExcluded(transaction.FieldMemo)
	return u
}

// ClearMemo clears the value of the "memo" field.
func (u *TransactionUpsert) ClearMemo() *TransactionUpsert {
	u.SetNull(transaction.FieldMemo)
	return u
}

// SetAmount sets the "amount" field.
func (u *TransactionUpsert) SetAmount(v uint64) *TransactionUpsert {
	u.Set(transaction.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateAmount() *TransactionUpsert {
	u.SetExcluded(transaction.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *TransactionUpsert) AddAmount(v uint64) *TransactionUpsert {
	u.Add(transaction.FieldAmount, v)
	return u
}

// ClearAmount clears the value of the "amount" field.
func (u *TransactionUpsert) ClearAmount() *TransactionUpsert {
	u.SetNull(transaction.FieldAmount)
	return u
}

// SetPayload sets the "payload" field.
func (u *TransactionUpsert) SetPayload(v []byte) *TransactionUpsert {
	u.Set(transaction.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *TransactionUpsert) UpdatePayload() *TransactionUpsert {
	u.SetExcluded(transaction.FieldPayload)
	return u
}

// ClearPayload clears the value of the "payload" field.
func (u *TransactionUpsert) ClearPayload() *TransactionUpsert {
	u.SetNull(transaction.FieldPayload)
	return u
}

// SetState sets the "state" field.
func (u *TransactionUpsert) SetState(v uint8) *TransactionUpsert {
	u.Set(transaction.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateState() *TransactionUpsert {
	u.SetExcluded(transaction.FieldState)
	return u
}

// AddState adds v to the "state" field.
func (u *TransactionUpsert) AddState(v uint8) *TransactionUpsert {
	u.Add(transaction.FieldState, v)
	return u
}

// ClearState clears the value of the "state" field.
func (u *TransactionUpsert) ClearState() *TransactionUpsert {
	u.SetNull(transaction.FieldState)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *TransactionUpsert) SetCreatedAt(v uint32) *TransactionUpsert {
	u.Set(transaction.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateCreatedAt() *TransactionUpsert {
	u.SetExcluded(transaction.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *TransactionUpsert) AddCreatedAt(v uint32) *TransactionUpsert {
	u.Add(transaction.FieldCreatedAt, v)
	return u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *TransactionUpsert) ClearCreatedAt() *TransactionUpsert {
	u.SetNull(transaction.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TransactionUpsert) SetUpdatedAt(v uint32) *TransactionUpsert {
	u.Set(transaction.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateUpdatedAt() *TransactionUpsert {
	u.SetExcluded(transaction.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *TransactionUpsert) AddUpdatedAt(v uint32) *TransactionUpsert {
	u.Add(transaction.FieldUpdatedAt, v)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TransactionUpsert) ClearUpdatedAt() *TransactionUpsert {
	u.SetNull(transaction.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TransactionUpsert) SetDeletedAt(v uint32) *TransactionUpsert {
	u.Set(transaction.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TransactionUpsert) UpdateDeletedAt() *TransactionUpsert {
	u.SetExcluded(transaction.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *TransactionUpsert) AddDeletedAt(v uint32) *TransactionUpsert {
	u.Add(transaction.FieldDeletedAt, v)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TransactionUpsert) ClearDeletedAt() *TransactionUpsert {
	u.SetNull(transaction.FieldDeletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Transaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(transaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TransactionUpsertOne) UpdateNewValues() *TransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(transaction.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Transaction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TransactionUpsertOne) Ignore() *TransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TransactionUpsertOne) DoNothing() *TransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TransactionCreate.OnConflict
// documentation for more info.
func (u *TransactionUpsertOne) Update(set func(*TransactionUpsert)) *TransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCoinType sets the "coin_type" field.
func (u *TransactionUpsertOne) SetCoinType(v int32) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetCoinType(v)
	})
}

// AddCoinType adds v to the "coin_type" field.
func (u *TransactionUpsertOne) AddCoinType(v int32) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.AddCoinType(v)
	})
}

// UpdateCoinType sets the "coin_type" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateCoinType() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateCoinType()
	})
}

// ClearCoinType clears the value of the "coin_type" field.
func (u *TransactionUpsertOne) ClearCoinType() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearCoinType()
	})
}

// SetNonce sets the "nonce" field.
func (u *TransactionUpsertOne) SetNonce(v uint64) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetNonce(v)
	})
}

// AddNonce adds v to the "nonce" field.
func (u *TransactionUpsertOne) AddNonce(v uint64) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.AddNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateNonce() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateNonce()
	})
}

// ClearNonce clears the value of the "nonce" field.
func (u *TransactionUpsertOne) ClearNonce() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearNonce()
	})
}

// SetUtxo sets the "utxo" field.
func (u *TransactionUpsertOne) SetUtxo(v []*sphinxplugin.Unspent) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetUtxo(v)
	})
}

// UpdateUtxo sets the "utxo" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateUtxo() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateUtxo()
	})
}

// ClearUtxo clears the value of the "utxo" field.
func (u *TransactionUpsertOne) ClearUtxo() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearUtxo()
	})
}

// SetPre sets the "pre" field.
func (u *TransactionUpsertOne) SetPre(v *sphinxplugin.Unspent) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetPre(v)
	})
}

// UpdatePre sets the "pre" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdatePre() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdatePre()
	})
}

// ClearPre clears the value of the "pre" field.
func (u *TransactionUpsertOne) ClearPre() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearPre()
	})
}

// SetTransactionType sets the "transaction_type" field.
func (u *TransactionUpsertOne) SetTransactionType(v int8) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetTransactionType(v)
	})
}

// AddTransactionType adds v to the "transaction_type" field.
func (u *TransactionUpsertOne) AddTransactionType(v int8) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.AddTransactionType(v)
	})
}

// UpdateTransactionType sets the "transaction_type" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateTransactionType() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateTransactionType()
	})
}

// ClearTransactionType clears the value of the "transaction_type" field.
func (u *TransactionUpsertOne) ClearTransactionType() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearTransactionType()
	})
}

// SetRecentBhash sets the "recent_bhash" field.
func (u *TransactionUpsertOne) SetRecentBhash(v string) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetRecentBhash(v)
	})
}

// UpdateRecentBhash sets the "recent_bhash" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateRecentBhash() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateRecentBhash()
	})
}

// ClearRecentBhash clears the value of the "recent_bhash" field.
func (u *TransactionUpsertOne) ClearRecentBhash() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearRecentBhash()
	})
}

// SetTxData sets the "tx_data" field.
func (u *TransactionUpsertOne) SetTxData(v []byte) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetTxData(v)
	})
}

// UpdateTxData sets the "tx_data" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateTxData() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateTxData()
	})
}

// ClearTxData clears the value of the "tx_data" field.
func (u *TransactionUpsertOne) ClearTxData() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearTxData()
	})
}

// SetTransactionID sets the "transaction_id" field.
func (u *TransactionUpsertOne) SetTransactionID(v string) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetTransactionID(v)
	})
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateTransactionID() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateTransactionID()
	})
}

// SetCid sets the "cid" field.
func (u *TransactionUpsertOne) SetCid(v string) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetCid(v)
	})
}

// UpdateCid sets the "cid" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateCid() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateCid()
	})
}

// ClearCid clears the value of the "cid" field.
func (u *TransactionUpsertOne) ClearCid() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearCid()
	})
}

// SetExitCode sets the "exit_code" field.
func (u *TransactionUpsertOne) SetExitCode(v int64) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetExitCode(v)
	})
}

// AddExitCode adds v to the "exit_code" field.
func (u *TransactionUpsertOne) AddExitCode(v int64) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.AddExitCode(v)
	})
}

// UpdateExitCode sets the "exit_code" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateExitCode() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateExitCode()
	})
}

// ClearExitCode clears the value of the "exit_code" field.
func (u *TransactionUpsertOne) ClearExitCode() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearExitCode()
	})
}

// SetName sets the "name" field.
func (u *TransactionUpsertOne) SetName(v string) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateName() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *TransactionUpsertOne) ClearName() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearName()
	})
}

// SetFrom sets the "from" field.
func (u *TransactionUpsertOne) SetFrom(v string) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetFrom(v)
	})
}

// UpdateFrom sets the "from" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateFrom() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateFrom()
	})
}

// ClearFrom clears the value of the "from" field.
func (u *TransactionUpsertOne) ClearFrom() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearFrom()
	})
}

// SetTo sets the "to" field.
func (u *TransactionUpsertOne) SetTo(v string) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetTo(v)
	})
}

// UpdateTo sets the "to" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateTo() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateTo()
	})
}

// ClearTo clears the value of the "to" field.
func (u *TransactionUpsertOne) ClearTo() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearTo()
	})
}

// SetMemo sets the "memo" field.
func (u *TransactionUpsertOne) SetMemo(v string) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetMemo(v)
	})
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateMemo() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateMemo()
	})
}

// ClearMemo clears the value of the "memo" field.
func (u *TransactionUpsertOne) ClearMemo() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearMemo()
	})
}

// SetAmount sets the "amount" field.
func (u *TransactionUpsertOne) SetAmount(v uint64) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *TransactionUpsertOne) AddAmount(v uint64) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateAmount() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateAmount()
	})
}

// ClearAmount clears the value of the "amount" field.
func (u *TransactionUpsertOne) ClearAmount() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearAmount()
	})
}

// SetPayload sets the "payload" field.
func (u *TransactionUpsertOne) SetPayload(v []byte) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdatePayload() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *TransactionUpsertOne) ClearPayload() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearPayload()
	})
}

// SetState sets the "state" field.
func (u *TransactionUpsertOne) SetState(v uint8) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetState(v)
	})
}

// AddState adds v to the "state" field.
func (u *TransactionUpsertOne) AddState(v uint8) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.AddState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateState() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateState()
	})
}

// ClearState clears the value of the "state" field.
func (u *TransactionUpsertOne) ClearState() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearState()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TransactionUpsertOne) SetCreatedAt(v uint32) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *TransactionUpsertOne) AddCreatedAt(v uint32) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateCreatedAt() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *TransactionUpsertOne) ClearCreatedAt() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TransactionUpsertOne) SetUpdatedAt(v uint32) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *TransactionUpsertOne) AddUpdatedAt(v uint32) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateUpdatedAt() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TransactionUpsertOne) ClearUpdatedAt() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TransactionUpsertOne) SetDeletedAt(v uint32) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *TransactionUpsertOne) AddDeletedAt(v uint32) *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TransactionUpsertOne) UpdateDeletedAt() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TransactionUpsertOne) ClearDeletedAt() *TransactionUpsertOne {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *TransactionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TransactionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TransactionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TransactionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TransactionUpsertOne.ID is not supported by MySQL driver. Use TransactionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TransactionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TransactionCreateBulk is the builder for creating many Transaction entities in bulk.
type TransactionCreateBulk struct {
	config
	builders []*TransactionCreate
	conflict []sql.ConflictOption
}

// Save creates the Transaction entities in the database.
func (tcb *TransactionCreateBulk) Save(ctx context.Context) ([]*Transaction, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Transaction, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = tcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TransactionCreateBulk) SaveX(ctx context.Context) []*Transaction {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TransactionCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Transaction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TransactionUpsert) {
//			SetCoinType(v+v).
//		}).
//		Exec(ctx)
func (tcb *TransactionCreateBulk) OnConflict(opts ...sql.ConflictOption) *TransactionUpsertBulk {
	tcb.conflict = opts
	return &TransactionUpsertBulk{
		create: tcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Transaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tcb *TransactionCreateBulk) OnConflictColumns(columns ...string) *TransactionUpsertBulk {
	tcb.conflict = append(tcb.conflict, sql.ConflictColumns(columns...))
	return &TransactionUpsertBulk{
		create: tcb,
	}
}

// TransactionUpsertBulk is the builder for "upsert"-ing
// a bulk of Transaction nodes.
type TransactionUpsertBulk struct {
	create *TransactionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Transaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(transaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TransactionUpsertBulk) UpdateNewValues() *TransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(transaction.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Transaction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TransactionUpsertBulk) Ignore() *TransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TransactionUpsertBulk) DoNothing() *TransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TransactionCreateBulk.OnConflict
// documentation for more info.
func (u *TransactionUpsertBulk) Update(set func(*TransactionUpsert)) *TransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCoinType sets the "coin_type" field.
func (u *TransactionUpsertBulk) SetCoinType(v int32) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetCoinType(v)
	})
}

// AddCoinType adds v to the "coin_type" field.
func (u *TransactionUpsertBulk) AddCoinType(v int32) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.AddCoinType(v)
	})
}

// UpdateCoinType sets the "coin_type" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateCoinType() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateCoinType()
	})
}

// ClearCoinType clears the value of the "coin_type" field.
func (u *TransactionUpsertBulk) ClearCoinType() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearCoinType()
	})
}

// SetNonce sets the "nonce" field.
func (u *TransactionUpsertBulk) SetNonce(v uint64) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetNonce(v)
	})
}

// AddNonce adds v to the "nonce" field.
func (u *TransactionUpsertBulk) AddNonce(v uint64) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.AddNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateNonce() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateNonce()
	})
}

// ClearNonce clears the value of the "nonce" field.
func (u *TransactionUpsertBulk) ClearNonce() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearNonce()
	})
}

// SetUtxo sets the "utxo" field.
func (u *TransactionUpsertBulk) SetUtxo(v []*sphinxplugin.Unspent) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetUtxo(v)
	})
}

// UpdateUtxo sets the "utxo" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateUtxo() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateUtxo()
	})
}

// ClearUtxo clears the value of the "utxo" field.
func (u *TransactionUpsertBulk) ClearUtxo() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearUtxo()
	})
}

// SetPre sets the "pre" field.
func (u *TransactionUpsertBulk) SetPre(v *sphinxplugin.Unspent) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetPre(v)
	})
}

// UpdatePre sets the "pre" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdatePre() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdatePre()
	})
}

// ClearPre clears the value of the "pre" field.
func (u *TransactionUpsertBulk) ClearPre() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearPre()
	})
}

// SetTransactionType sets the "transaction_type" field.
func (u *TransactionUpsertBulk) SetTransactionType(v int8) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetTransactionType(v)
	})
}

// AddTransactionType adds v to the "transaction_type" field.
func (u *TransactionUpsertBulk) AddTransactionType(v int8) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.AddTransactionType(v)
	})
}

// UpdateTransactionType sets the "transaction_type" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateTransactionType() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateTransactionType()
	})
}

// ClearTransactionType clears the value of the "transaction_type" field.
func (u *TransactionUpsertBulk) ClearTransactionType() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearTransactionType()
	})
}

// SetRecentBhash sets the "recent_bhash" field.
func (u *TransactionUpsertBulk) SetRecentBhash(v string) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetRecentBhash(v)
	})
}

// UpdateRecentBhash sets the "recent_bhash" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateRecentBhash() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateRecentBhash()
	})
}

// ClearRecentBhash clears the value of the "recent_bhash" field.
func (u *TransactionUpsertBulk) ClearRecentBhash() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearRecentBhash()
	})
}

// SetTxData sets the "tx_data" field.
func (u *TransactionUpsertBulk) SetTxData(v []byte) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetTxData(v)
	})
}

// UpdateTxData sets the "tx_data" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateTxData() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateTxData()
	})
}

// ClearTxData clears the value of the "tx_data" field.
func (u *TransactionUpsertBulk) ClearTxData() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearTxData()
	})
}

// SetTransactionID sets the "transaction_id" field.
func (u *TransactionUpsertBulk) SetTransactionID(v string) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetTransactionID(v)
	})
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateTransactionID() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateTransactionID()
	})
}

// SetCid sets the "cid" field.
func (u *TransactionUpsertBulk) SetCid(v string) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetCid(v)
	})
}

// UpdateCid sets the "cid" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateCid() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateCid()
	})
}

// ClearCid clears the value of the "cid" field.
func (u *TransactionUpsertBulk) ClearCid() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearCid()
	})
}

// SetExitCode sets the "exit_code" field.
func (u *TransactionUpsertBulk) SetExitCode(v int64) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetExitCode(v)
	})
}

// AddExitCode adds v to the "exit_code" field.
func (u *TransactionUpsertBulk) AddExitCode(v int64) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.AddExitCode(v)
	})
}

// UpdateExitCode sets the "exit_code" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateExitCode() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateExitCode()
	})
}

// ClearExitCode clears the value of the "exit_code" field.
func (u *TransactionUpsertBulk) ClearExitCode() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearExitCode()
	})
}

// SetName sets the "name" field.
func (u *TransactionUpsertBulk) SetName(v string) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateName() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *TransactionUpsertBulk) ClearName() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearName()
	})
}

// SetFrom sets the "from" field.
func (u *TransactionUpsertBulk) SetFrom(v string) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetFrom(v)
	})
}

// UpdateFrom sets the "from" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateFrom() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateFrom()
	})
}

// ClearFrom clears the value of the "from" field.
func (u *TransactionUpsertBulk) ClearFrom() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearFrom()
	})
}

// SetTo sets the "to" field.
func (u *TransactionUpsertBulk) SetTo(v string) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetTo(v)
	})
}

// UpdateTo sets the "to" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateTo() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateTo()
	})
}

// ClearTo clears the value of the "to" field.
func (u *TransactionUpsertBulk) ClearTo() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearTo()
	})
}

// SetMemo sets the "memo" field.
func (u *TransactionUpsertBulk) SetMemo(v string) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetMemo(v)
	})
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateMemo() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateMemo()
	})
}

// ClearMemo clears the value of the "memo" field.
func (u *TransactionUpsertBulk) ClearMemo() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearMemo()
	})
}

// SetAmount sets the "amount" field.
func (u *TransactionUpsertBulk) SetAmount(v uint64) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *TransactionUpsertBulk) AddAmount(v uint64) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateAmount() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateAmount()
	})
}

// ClearAmount clears the value of the "amount" field.
func (u *TransactionUpsertBulk) ClearAmount() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearAmount()
	})
}

// SetPayload sets the "payload" field.
func (u *TransactionUpsertBulk) SetPayload(v []byte) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdatePayload() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *TransactionUpsertBulk) ClearPayload() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearPayload()
	})
}

// SetState sets the "state" field.
func (u *TransactionUpsertBulk) SetState(v uint8) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetState(v)
	})
}

// AddState adds v to the "state" field.
func (u *TransactionUpsertBulk) AddState(v uint8) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.AddState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateState() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateState()
	})
}

// ClearState clears the value of the "state" field.
func (u *TransactionUpsertBulk) ClearState() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearState()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TransactionUpsertBulk) SetCreatedAt(v uint32) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *TransactionUpsertBulk) AddCreatedAt(v uint32) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateCreatedAt() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *TransactionUpsertBulk) ClearCreatedAt() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TransactionUpsertBulk) SetUpdatedAt(v uint32) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *TransactionUpsertBulk) AddUpdatedAt(v uint32) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateUpdatedAt() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TransactionUpsertBulk) ClearUpdatedAt() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TransactionUpsertBulk) SetDeletedAt(v uint32) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *TransactionUpsertBulk) AddDeletedAt(v uint32) *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TransactionUpsertBulk) UpdateDeletedAt() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TransactionUpsertBulk) ClearDeletedAt() *TransactionUpsertBulk {
	return u.Update(func(s *TransactionUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *TransactionUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TransactionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TransactionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TransactionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
