apiVersion: apps/v1
kind: Deployment
metadata:
  name: sphinx-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sphinx-proxy
  template:
    metadata:
      labels:
        app: sphinx-proxy
    spec:
      containers:
      - name: sphinx-proxy
        image: uhub.service.ucloud.cn/entropypool/sphinx-proxy:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: sphinx-proxy
  namespace: kube-system
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: h2c

spec:
  ports:
  - name: grpc
    port: 50001
  selector:
    app: sphinx-proxy
  - name: http
    port: 50000
  selector:
    app: sphinx-proxy

