apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-sample
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-sample
  template:
    metadata:
      labels:
        app: service-sample
    spec:
      containers:
      - name: service-sample
        image: entropypool/service-sample:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: service-sample
  namespace: kube-system
spec:
  ports:
  - name: api
    port: 8080
