apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sphinx-proxy-npool-top-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: sphinx-proxy-npool
    k8s.kuboard.cn/workload: sphinx-proxy-npool
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/service.serversscheme: h2c

spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`sphinx.proxy.api.npool.top`)
      kind: Rule
      services:
        - name: sphinx-proxy
          #This port will causing the fallback to "http" scheme instead of "https"
          port: 50001
          scheme: h2c