apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sphinx-proxy-npool-top-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: sphinx-proxy-npool
    k8s.kuboard.cn/workload: sphinx-proxy-npool
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.http.services.sphinx-proxy.loadbalancer.server.scheme: h2c

spec:
  rules:
    - host: sphinx.proxy.api.npool.top
      http:
        paths:
          - path: /
            backend:
              serviceName: sphinx-proxy
              servicePort: 50001

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sphinx-proxy-xpool-top-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: sphinx-proxy-xpool
    k8s.kuboard.cn/workload: sphinx-proxy-xpool
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    # traefik.ingress.kubernetes.io/service.serversscheme: h2c
    traefik.http.services.sphinx-proxy.loadbalancer.server.scheme: h2c

spec:
  rules:
    - host: sphinx.proxy.api.xpool.top
      http:
        paths:
          - path: /
            backend:
              serviceName: sphinx-proxy
              servicePort: 50001
