apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sphinx-proxy-npool-top-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: sphinx-proxy-npool
    k8s.kuboard.cn/workload: sphinx-proxy-npool
    kubernetes.io/ingress.class: "traefik-internet"

spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Headers(`content-type`,`application/grpc`) && Host(`sphinx.proxy.api.npool.top`)
      kind: Rule
      services:
        - name: sphinx-proxy
          port: 50001
          scheme: h2c

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sphinx-proxy-xpool-top-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: sphinx-proxy-xpool
    k8s.kuboard.cn/workload: sphinx-proxy-xpool
    kubernetes.io/ingress.class: "traefik-internet"

spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Headers(`content-type`,`application/grpc`) && Host(`sphinx.proxy.api.xpool.top`)
      kind: Rule
      priority: 50
      services:
        - name: sphinx-proxy
          port: 50001
          scheme: h2c
