apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sphinx-proxy-npool-top-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: sphinx-proxy-npool
    k8s.kuboard.cn/workload: sphinx-proxy-npool
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-strip-sphinx-proxy-prefix@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http:
        paths:
          - path: /sphinx-proxy
            backend:
              serviceName: sphinx-proxy
              servicePort: 32759

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sphinx-proxy-xpool-top-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: sphinx-proxy-xpool
    k8s.kuboard.cn/workload: sphinx-proxy-xpool
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-strip-sphinx-proxy-prefix@kubernetescrd

spec:
  rules:
    - host: api.xpool.top
      http:
        paths:
          - path: /sphinx-proxy
            backend:
              serviceName: sphinx-proxy
              servicePort: 32759

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-sphinx-proxy-prefix
  namespace: kube-system
spec:
  stripPrefix:
    prefixes:
      - /sphinx-proxy
